services:
  php:
    build:
      context: .
    environment:
      PHP_OPCACHE_ENABLE: "1"
      AUTORUN_ENABLED: true
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"


  queue:
    build:
      context: .
    command: [ "php", "/var/www/html/artisan", "queue:work", "--tries=3" ]
    healthcheck:
      test: [ "CMD", "healthcheck-queue" ]
      start_period: 10s
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"


volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
