GET http://localhost:80/api/user
Accept: application/json
Authorization: Bearer 13|sW42qSTvLB0hciFjpc9ckfFpN4sA8OZlnHaqAN3P3d85a007

###


POST http://localhost:80/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Callum",
    "email": "cwellkane@gmail.com",
    "password": "Test@12345"
}

###


POST http://localhost:80/api/login
Content-Type: application/json
Accept: application/json

{
    "name": "Callum",
    "email": "cwellkane@gmail.com",
    "password": "Test@12345"
}

###

POST http://localhost:80/api/expenses
Content-Type: application/json
Accept: application/json
Authorization: Bearer 13|sW42qSTvLB0hciFjpc9ckfFpN4sA8OZlnHaqAN3P3d85a007

{
    "name": "This is a test expense",
    "amount": 45
}
