GET http://localhost:80/api/user
Accept: application/json
Authorization: Bearer 8|wftWlSUN2Dg1x0Qe8UcUveLF2ZxgQqvHEo1wvmG015907b75

###


POST http://localhost:80/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Callum",
    "email": "cwellkane@gmail.com",
    "password": "Test@12345"
}

###


POST http://localhost:80/api/login
Content-Type: application/json

{
    "name": "Callum",
    "email": "cwellkane@gmail.com",
    "password": "Test@12345"
}

###

